---
namespace: fmjstudios
name: databases
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for database setup and configuration
license_file: "LICENSE"
tags:
  - database
  - tcp
  - tls
  - redis
  - mysql
  - postgresql
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github