---
__varnish_package_name: varnish
__varnish_dependencies:
  - debian-archive-keyring
  - curl
  - gnupg
  - apt-transport-https

__varnish_tmp_path: /tmp/varnish

__varnish_gpg_key_url: "https://packagecloud.io/varnishcache/varnish{{ varnish_version }}/gpgkey"
__varnish_gpg_key_file_name: varnish.gpg

__varnish_gpg_key_tmp_path: "{{ __varnish_tmp_path }}/{{ __varnish_gpg_key_file_name }}"
__varnish_gpg_key_install_path: "/etc/apt/keyrings/{{ __varnish_gpg_key_file_name }}"

__varnish_gpg_key_tmp_keyring: "{{ __varnish_tmp_path }}/tmp-keyring.gpg"

__varnish_sources_install_path: /etc/apt/sources.list.d/varnishcache_varnish60lts.list
__varnish_sources_pin_path: /etc/apt/preferences.d/varnishcache

__varnish_conf_dir: /etc/varnish
__varnish_secret_path: "{{ __varnish_conf_dir }}/varnish_secret"

__varnish_systemd_service: varnish
__varnish_systemd_path: /etc/systemd/system
__varnish_systemd_alternate_path: /lib/systemd/system
__varnish_system_default_path: /etc/default

# Architecture configuration for sources.list.d/...
_go_arch_map:
  i386: "386"
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "armv7"
  armv6l: "armv6"

_go_arch: "{{ _go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
