---
# Can be 'source' or 'repo' depending on whether or not full installation from source or from the Redis repositories
# should be done. Default is 'source' due to the fact that regular systemd from the repositories does not support
# systemd
redis_package_source: source

# Include more Redis configuration files
redis_includes:
  []
  # - /path/to/local.conf

# Redis modules to include for extra functionality
redis_modules:
  []
  # - loadmodule /path/to/other_module.so

redis_system_users:
  []
  # - ar

redis_users:
  []
  # - "user ar on #<HASH> ~* &* +@all"

redis_bind_interface: "127.0.0.1 -::1"
redis_protected_mode: "yes"

redis_port: 6379
redis_timeout: 0

redis_databases: 16

redis_tcp_backlog: 511
redis_tcp_keepalive: 300

redis_enable_protected_configs: "no"
redis_enable_debug_command: "no"
redis_enable_module_command: "no"

redis_supervised: auto
redis_pidfile: /var/run/redis/redis.pid

redis_loglevel: notice
redis_logfile: /var/log/redis/redis.log

redis_locale_collate: en_US.UTF-8

redis_syslog_enabled: "no"
redis_syslog_ident: redis
redis_syslog_facility: local0

redis_crash_log_enabled: "no"
redis_crash_memcheck_enabled: "no"

redis_always_show_logo: "yes"
redis_set_proc_title: "yes"
redis_proc_title_template: "{title} {listen-addr} {port} {tls-port} {server-mode} {config-file}"

redis_tls_enable: "false"
redis_tls_port: 6379
redis_tls_cert_file: redis-cert.pem
redis_tls_key_file: redis-key.pem
redis_tls_key_file_pass: secret
redis_tls_auth_clients: "no"
redis_tls_protocols: "TLSv1.2 TLSv1.3"
redis_tls_session_caching: "no"
redis_tls_session_cache_size: 5000
redis_tls_session_cache_timeout: 60
redis_tls_extra_configuration: ""
# Example extra tls configuration:
#    redis_tls_extra_configuration: |
#      tls-client-cert-file client.crt
#      tls-client-key-file client.key
#      tls-client-key-file-pass secret
#      tls-dh-params-file redis.dh
#      tls-ca-cert-file ca.crt
#      tls-ca-cert-dir /etc/ssl/certs
#      tls-replication yes
#      tls-cluster yes
#      tls-ciphers DEFAULT:!MEDIUM
#      tls-ciphersuites TLS_CHACHA20_POLY1305_SHA256
#      tls-prefer-server-ciphers yes

redis_save:
  - 3600 1
  - 300 100
  - 60 10000
redis_stop_writes_on_bgsave_error: "yes"
redis_rdbcompression: "yes"
redis_rdbchecksum: "yes"
redis_red_del_sync_files: "no"
redis_sanitize_dump_payload: "no"
redis_dbfilename: dump.rdb
redis_dbdir: /var/lib/redis

redis_replication_config: ""
# Example replication configuration:
#    redis_replication_config: |
#    replicaof <masterip> <masterport>
#    masterauth <master-password>
#    masteruser <username>
#    replica-serve-stale-data yes
#    replica-read-only yes
#    repl-diskless-sync yes
#    repl-diskless-sync-max-replicas 0
#    repl-diskless-load disabled
#    repl-ping-replica-period 10
#    repl-timeout 60
#    repl-disable-tcp-nodelay no
#    repl-backlog-size 1mb
#    repl-backlog-ttl 3600
#    replica-priority 100
#    propagation-error-behavior ignore
#    replica-ignore-disk-write-errors no
#    replica-announced yes
#    min-replicas-to-write 0
#    min-replicas-max-lag 10
#    replica-announce-ip 5.5.5.5
#    replica-announce-port 1234

redis_tracking_table_max_keys: 1000000

redis_acl_log_max_len: 128
redis_acl_file: ""
redis_acl_pubsub_default: resetchannels
redis_requirepass: ""

redis_max_clients: 10000

redis_max_memory: 0
redis_max_memory_policy: noeviction
redis_max_memory_samples: 5
redis_max_memory_eviction_tenacity: 10
redis_active_expire_effort: 1
redis_replica_ignore_max_memory: "yes"

redis_appendonly: "no"
redis_appendfsync: everysec
redis_no_appendfsync_on_rewrite: "no"
